### ISSUE TITLE
Data access

### ISSUE THREAD

**Issue by RoboDonut** [randel/COVID-19-US-county-map#1]
Can you provide access to the geojson you are creating? alternatively do you have a repo for the data extraction?

**Comment by RoboDonut** [comment]
nm, fond another source

**Comment by randel** [comment]
I am updating [the number of cases per county](https://github.com/randel/COVID-19-US-county-map/blob/master/data.csv) from now on.

1. This has been manually corrected for typos and duplicated rows when they appear. 
2. Unassigned cases are not shown. 
3. For Grand/Diamond Princess, cases assigned to counties of Bexar and San Diego are included in the corresponding states Texas and California.
4. Utah has combined health departments, e.g., [Southwest Utah](https://swuhealth.org/aboutswuphd/) for five counties. Those cases are assigned as unknown without more details for now.

**Comment by RoboDonut** [comment]
yes, that is the alternative source i found as well. thank you
