### ISSUE TITLE
data removed

### ISSUE THREAD

**Issue by chenwang-dr** [randel/COVID-19-US-county-map#2]
Hi,

Was using your dataset to build county level model. Sad to see you have took it down. Do you have plans to put it back on? Thank you!

**Comment by randel** [comment]
Sorry about this. I found it no longer proper to share the data publicly after noticing that 1Point3Acres is providing [COVID-19 Data Access Application](https://docs.google.com/forms/d/e/1FAIpQLScMGcazASoCxrcYJuBRxlOsAtpeTeyz1YWXJdZxPnFzbNvZRA/viewform).

It explicitly states: "Please direct data requests to this form - no redistribution of our data please (we worked really hard to curate it)."

Glad to hear that you are using the data to build a model. Feel free to let me know if you encounter any issue with the data application. Interested to hear about your model when you are ready to share.

**Comment by chenwang-dr** [comment]
Thank you!
