### ISSUE TITLE
Data Update Mechanism

### ISSUE THREAD

**Issue by antong314** [randel/COVID-19-US-county-map#3]
Curious, how is the underlying data actually updated? I understand the source, but I don't see the code that pulls the data from the source, just large index.html updates, assume there is some other mechanism that is doing this in another project?

**Comment by randel** [comment]
Yes, I am crawling the data. Previously I published the updated data file, but stopped after the source provided API (see below). Please let me know if you have any problem obtaining the data.
https://github.com/randel/COVID-19-US-county-map/issues/2
